### ISSUE TITLE
Change in OS style names

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/ostranslator-ii#29] opened 2017-03-29 11:18 UTC
For schema 7, it is topographicarea.qml, etc but now you have multiple options topographicarea-backdrop.qml, topographicarea-light.qml, topographicarea-standard.qml

I think we should use topographicarea-standard.qml styes.

**Comment by PeterPetrik** [comment] 2017-04-07 05:33
we do, duplicate of #31

**Comment by PeterPetrik** [comment] 2017-05-10 11:17
fixed in 1.4.2

**Closed** 2017-05-10 11:16 UTC
Labels: bug, duplicate
